import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import MainImage from "../public/mainPageMainImage.png";
import TrainingImg from "../public/telim1.png";
import TrainingImg2 from "../public/telimBg-2.png";
import TrainingImg3 from "../public/telimBg-3.png";
import ServicesCard1 from "../public/servicesCard1.png";
import ServicesCard2 from "../public/servicesCard2.png";
import ServicesCard3 from "../public/servicesCard3.png";
import SislatLogo from "../public/SislatLogo.png";
import Sislat1 from "../public/sislat1.png";
import Sislat2 from "../public/sislat2.png";
import Sislat3 from "../public/sislat3.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="main-section">
          <div className="main-section-context container">
            <div className="main-section-image">
              <Image src={MainImage} alt="Main Page" />
            </div>
            <div className="main-section-text">
              <h2>Kibertəhlükəsizlik səviyyəsini dünya miqyasında zirvələrə daşıyacayıq.</h2>
              <div className="text-button">
                <Link href={"/about"}>Ətraflı</Link>
              </div>
            </div>
          </div>
        </section>
        <section className="training">
          <div className="training-context container">
            <h1>Təlim-Tədris</h1>
            <div className="training-text-image">
              <div className="training-image">
                <Image src={TrainingImg} alt="training" />
              </div>
              <div className="training-test">
                <h4>Peşəkar mütəxəssis hazırlığı</h4>
                <p>Peşəkar mütəxəssislərimizin nəzəri və təcrübi biliklərindən faydalanaraq mütəxəssis hazırlığına qoşulun</p>
                <Link href={"/education/preparation"}>Ətraflı</Link>
              </div>
            </div>
            <div className="training-text-image">
              <div className="training-test">
                <h4>Korporativ Təlimlər</h4>
                <p>
                  Müəssəliriniz İT infrastrukturunun təhlüksəzliyinin təmini məqsədilə əməkdaşlarınızı qısa müddətli kibert təhlükəsizlik təlimlərinə
                  cəlb edin
                </p>
                <Link href={"/education/training"}>Ətraflı</Link>
              </div>
              <div className="training-image">
                <Image src={TrainingImg2} alt="training" />
              </div>
            </div>
            <div className="training-text-image">
              <div className="training-image">
                <Image src={TrainingImg3} alt="training" />
              </div>
              <div className="training-test">
                <h4>Akademik fəaliyyət</h4>
                <p>
                  Cybernetics MMC yerli və xarici universitetlərlə əməkdaşlıq edərəkbakalavr və magistr təhsil səviyyəsində tədrisin təşkili və
                  laboratiyanın qurulmasını həyata keçirir.
                </p>
                <Link href={"/education/academic-activity"}>Ətraflı</Link>
              </div>
            </div>
          </div>
        </section>
        <section className="services">
          <div className="services-top">
            <div className="services-text">
              <h1>Xidmətlər</h1>
              <p>
                Cybernetics MMC dövlət qurumlarına və korporativ müəssisələrə bir neçə istiqamətlərdə kibertəhlükəsizlik həllərinin təmini məqsədilə
                xidmətlər təklif edir
              </p>
            </div>
          </div>
          <div className="services-bottom">
            <div className="services-bottom-context container">
              <div className="card">
                <h4>Nüfuzetmə testi</h4>
                <div className="services-image">
                  <Image src={ServicesCard1} alt={"Service"} />
                </div>
                <p>
                  Müəssinizdə nüfuzetmə testini həyata keçirərək kiber hücumlarla bağlı risk göstəricilərini əks etirən hesabat və təklifləri təqim
                  edirik.
                </p>
                <Link href={"/services/penetrationTesting"}>Ətraflı</Link>
              </div>
              <div className="line-wrapper">
                {" "}
                <div className="line"></div>{" "}
              </div>
              <div className="card">
                <h4>Şəbəkə arxitekturası</h4>
                <div className="services-image">
                  <Image src={ServicesCard2} alt={"Service"} />
                </div>
                <p>Müəssini İT və şəbəkə infrastrukturunu yeni və ya formalaşdırmaq istəyirsinizmi? O zaman bizə müraciət edə bilərsiniz.</p>
                <Link href={"#"}>Ətraflı</Link>
              </div>
              <div className="line-wrapper">
                {" "}
                <div className="line"></div>{" "}
              </div>
              <div className="card">
                <h4>İT dəstək</h4>
                <div className="services-image">
                  <Image src={ServicesCard3} alt={"Service"} />
                </div>
                <p>
                  Müəssisənizdə yaranan İT problemlərinin mütəxəssislər tərəfində həllini və bu problemlərə qarşı nəzarət edəcək mütəxəssislərə
                  ehtiyacınız varsa Cybernetics MMC-ə müraciət edə bilərsiniz.
                </p>
                <Link href={"#"}>Ətraflı</Link>
              </div>
            </div>
          </div>
        </section>
        <section className="sislat">
          <div className="sislat-context container">
            <div className="sislat-image">
              <Image src={SislatLogo} alt="SislatLogo" />
            </div>{" "}
            <p>
              Cybernetics MMC bütün kibertəhlükəsizlik avadanlıqlarını və məhsullarını milliləşdirməyi hədəfləyən bir şirkətdir ki, Sislat brendi bu
              məhsullardan ilkidir.
            </p>
            <Link href={"/sislat"}>Ətraflı</Link>
          </div>
        </section>
        <section className="sislat-cards">
          <div className="sislat-context container">
            <div className="card">
              <h4>Sislat Firewall</h4>
              <div className="sislat-card-image">
                <Image src={Sislat1} alt="sislat card" />
              </div>
              <div className="card-text">
                {" "}
                <p>IDS/IPS, Firewall, URl filtrləmə, Applikasiya filtrləmə, VPN və s. özəlliklər</p>
              </div>
              <Link href={"#"}>Ətraflı</Link>
            </div>
            <div className="line-container">
              <div className="line"></div>
            </div>
            <div className="card">
              <h4>Sislat hotspot</h4>
              <div className="sislat-card-image">
                <Image src={Sislat2} alt="sislat card" />
              </div>
              <div className="card-text">
                {" "}
                <p>SMS, Otel proqram təminatı, Sponsor tipli girişlər, loglama və s. özəlliklər</p>
              </div>
              <Link href={"#"}>Ətraflı</Link>
            </div>
            <div className="line-container">
              <div className="line"></div>
            </div>
            <div className="card">
              <h4>Sislat 2FA</h4>
              <div className="sislat-card-image">
                <Image src={Sislat3} alt="sislat card" />
              </div>
              <div className="card-text">
                {" "}
                <p> VPN qoşulmar üçün sms və ya google autoidentifikator ilə 2-ci təsdiqləmə həyata keçirir.</p>
              </div>{" "}
              <Link href={"#"}>Ətraflı</Link>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
